server:
   port: 9091
   servlet:
      context-path: /crud-h2-api
    
logging:
   file:
      name: crud-h2-api.log
   level:
      org:
         hibernate:
            type: trace
            stat: debug

spring:
   application:
      name: crud-h2-api        
   boot:
      admin:
         client:
            enabled: false
            autoRegistration: true
            url: http://localhost:9092/
#Hibernet and H2 db configurations
   datasource:
      url: jdbc:h2:file:./h2_db_file
      driverClassName: org.h2.Driver
      username: sa
      password:
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect 
#create database schema from SQL files
      hibernate.ddl-auto: update
#Turn Statistics on and log SQL stmts
      show-sql: true
      properties:
         hibernate:
            format_sql: true
            generate_statistics: false
#Enabling H2 Console
   h2:
      console:
         enabled: true 
#Custom H2 Console URL
         path: /h2-console
 

 




      




